### ISSUE TITLE
Integration of /jp/job, /en/job

### ISSUE THREAD

**Issue by nishidai-andaze** [andaze/WebCorporate#46]
# Current Status

- The repository is managed at https://github.com/andaze/hugo-jobs.
- config baseUrl is https://www.andaze.com/job/. Therefore, the internal PATH of the generated HUGO is /job/en, /job/en.
- Using netlify's redirect setting (or making full use of the routing function), access to /en/job, /ja/job is implemented to work like an alias (I don't know the specific configuration details or flow of operation).

# Problem

- Should be simple with static site, but there is a netlify dependency around redirects (doesn't work with other hosting services?)

# Strategy

- Add https://github.com/andaze/hugo-jobs to this repository as a git submodule and deploy the two repositories built & merged when deploying to azure static web app
- PATH https://www.andaze.com/job/ to /en/job/~~, /en/job/~~ so that the first layer of the content dir structure is only the /job section

**Comment by nishidai-andaze** [comment]
既存サイトも実はサブディレクトリ配下が別のHUGOで作られているとのこと

とりあえずメインプロジェクトからは除外し、最後にいい塩梅で見れるようにしたあと、取り込めるようにする

**Comment by nishidai-andaze** [comment]
content/job とディレクトリ構成を変更することでとりあえずパーマリンクなどの生成は問題がない。
ちとばかしスタイルがおかしい。
原因はアセットビルドあたりの模様

**Comment by nishidai-andaze** [comment]
@ameio  [ background-image: url("./images/slider1.webp");](https://github.com/andaze/hugo-jobs/blob/5ff764dae92b1a173fc68e56866a94554f794fa6/themes/andazejob/assets/css/custom.css#L367) 
I can't find this file in the corresponding repository, where does the file entity exist?

**Comment by ameio-developer** [comment]
> @ameio [ background-image: url("./images/slider1.webp");](https://github.com/andaze/hugo-jobs/blob/5ff764dae92b1a173fc68e56866a94554f794fa6/themes/andazejob/assets/css/custom.css#L367)
> 
> I can't find this file in the corresponding repository, where does the file entity exist?
> 
> Tweet It seems strange to talk about another repository here, but since the purpose of this project is to integrate with the corporate site, it is okay.

We check this things

we can not use this image 



in below short code file we can override images 

https://github.com/andaze/hugo-jobs/blob/5ff764dae92b1a173fc68e56866a94554f794fa6/themes/andazejob/layouts/shortcodes/subpagetopimage.html#L72




so if you can remove from custom.css file then remove  

it cant affect to our design

**Comment by ameio** [comment]
@nishidai-andaze 
Add https://github.com/andaze/hugo-jobs to this repository as a git submodule and deploy the two repositories built & merged when deploying to azure static web app
PATH https://www.andaze.com/job/ to /en/job/, /en/job/ so that the first layer of the content dir structure is only the /job section
==============
If you change this then your website url will look like following

**Old**
https://www.andaze.com/ja/job/

**After change (New change)** 
https://www.andaze.com/job/ja


So your new change will break consistency of your corporate site which is currently following
https://www.andaze.com/ja/about/
https://www.andaze.com/ja/services/

**Our suggestion** 
current code of Job site there is only routing redirect which available in all hosting provider
so it is not big challenge

But still if you thing setup sub module then we need to think more how it will work

**Comment by nishidai-andaze** [comment]
> Our suggestion
> current code of Job site there is only routing redirect which available in all hosting provider
> so it is not big challenge

Am I correct in understanding that the following instructions should be followed for Azure?
https://docs.microsoft.com/ja-jp/azure/static-web-apps/configuration

Also, it looks like netlify.toml and _redirects are currently in charge of redirects, is there any documentation on these?
If so, please provide a link.

**Comment by ameio** [comment]
@nishidai-andaze 
yes your understand correctly 

for document i will check at my end then let you know
